apiVersion: v1
kind: Secret
metadata:
  name:
    grotesque-secret
type: Opaque
data:
  # kubectl get secret X -o yaml + base64 -d to read secret
  tsi_serviceprincipal_clientid: #LOOK_ME_UP_IN_PORTAL#
  tsi_serviceprincipal_secret: #LOOK_ME_UP_IN_PORTAL#