# Values for development environment for grotesque.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicas: 1
image:
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 1
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /grotesque