# Values for staging environment for grotesque.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicas: 1
image:
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 1
ingress:
  enabled: true
  path: /api/grotesque
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
prometheus:
  scrape: true
app:
  # Defined in Azure portal app registration
  tsi_serviceprincipal_clientid: 8bb15f24-954e-457f-9afb-7ba787c78270
  tsi_environment_fqdn: a662fc52-8230-41a8-a78e-e5c59186e933.env.timeseries.azure.com
  asp_environment: Staging
