{{- if not .Values.secret.existing -}}
apiVersion: v1
kind: Secret
metadata:
  name:
    {{ .Release.Name }}-secret
  annotations:
    # add this secret via a hook rather than a regular template - otherwise the template re-executes during upgrade/rollback creating new "passwords"
    # FIXME: secret does not get delete with 'helm delete' (due to it being a hook) - re-installing the release fails, see CO-1247
    "helm.sh/hook": pre-install
type: Opaque
data:
  # kubectl get secret X -o yaml + base64 -d to read secret
  tsi_serviceprincipal_clientid: #LOOK_ME_UP_IN_PORTAL#
  tsi_serviceprincipal_secret: #LOOK_ME_UP_IN_PORTAL#
{{- end -}}